
import json


match_details = {
    "hlac name":"freedom",
    "n of artworks tagged with it":40,
    "artworks tagged with it":[
        "A01061",
        "A01062",
        "A01063",
        "AR00287",
        "N03696",
        "N04415",
        "P01898",
        "P01915",
        "P01916",
        "P11018",
        "P11020",
        "P11945",
        "P77393",
        "P77693",
        "T01513",
        "T02186",
        "T02187",
        "T02332",
        "T03388",
        "T03495",
        "T03512",
        "T03514",
        "T03515",
        "T03594",
        "T06562",
        "T06563",
        "T06572",
        "T07906",
        "T12026",
        "T12321",
        "T12430",
        "T12431",
        "T12432",
        "T12434",
        "T12435",
        "T12573",
        "T12748",
        "T12989",
        "T13312",
        "T13425"
    ],
    "tagged_artworks_dict":{
        "A01061":{
            "url":"http://www.tate.org.uk/art/artworks/butler-study-for-head-of-watcher-a01061",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/A/A01/A01061_8.jpg",
            "thumbnailCopyright":"\u00a9 The estate of Reg Butler",
            "concept_names":[
                "subject",
                "objects",
                "fine art and design, named works",
                "Butler, Reg, 'The Unknown Political Prisoner'",
                "abstraction",
                "from recognisable sources",
                "figure",
                "society",
                "social comment",
                "freedom",
                "persecution",
                "government and politics",
                "political prisoner",
                "people",
                "actions: expressive",
                "grimacing",
                "body",
                "head / face",
                "actions: processes and functions",
                "looking / watching",
                "actions: postures and motions",
                "looking up",
                "adults",
                "woman"
            ]
        },
        "A01062":{
            "url":"http://www.tate.org.uk/art/artworks/butler-study-for-head-of-watcher-a01062",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/A/A01/A01062_8.jpg",
            "thumbnailCopyright":"\u00a9 The estate of Reg Butler",
            "concept_names":[
                "subject",
                "objects",
                "fine art and design, named works",
                "Butler, Reg, 'The Unknown Political Prisoner'",
                "abstraction",
                "from recognisable sources",
                "figure",
                "society",
                "social comment",
                "freedom",
                "persecution",
                "government and politics",
                "political prisoner",
                "people",
                "actions: expressive",
                "grimacing",
                "body",
                "head / face",
                "actions: processes and functions",
                "looking / watching",
                "actions: postures and motions",
                "looking up",
                "adults",
                "woman"
            ]
        },
        "A01063":{
            "url":"http://www.tate.org.uk/art/artworks/butler-study-for-head-of-watcher-a01063",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/A/A01/A01063_8.jpg",
            "thumbnailCopyright":"\u00a9 The estate of Reg Butler",
            "concept_names":[
                "subject",
                "objects",
                "fine art and design, named works",
                "Butler, Reg, 'The Unknown Political Prisoner'",
                "abstraction",
                "from recognisable sources",
                "figure",
                "society",
                "social comment",
                "freedom",
                "persecution",
                "government and politics",
                "political prisoner",
                "people",
                "actions: expressive",
                "grimacing",
                "body",
                "head / face",
                "actions: processes and functions",
                "looking / watching",
                "actions: postures and motions",
                "looking up",
                "adults",
                "woman"
            ]
        },
        "AR00287":{
            "url":"http://www.tate.org.uk/art/artworks/warhol-statue-of-liberty-ar00287",
            "thumbnailUrl":"null",
            "thumbnailCopyright":"null",
            "concept_names":[
                "subject",
                "places",
                "cities, towns, villages (non-UK)",
                "New York, Statue of Liberty",
                "society",
                "lifestyle and culture",
                "cultural icon",
                "social comment",
                "freedom",
                "government and politics",
                "patriotism",
                "symbols & personifications",
                "inscriptions",
                "dedication",
                "emotions, concepts and ideas",
                "formal qualities",
                "photographic",
                "repetition",
                "objects",
                "reading, writing, printed matter",
                "placard",
                "abstraction",
                "non-representational",
                "text"
            ]
        },
        "N03696":{
            "url":"http://www.tate.org.uk/art/artworks/blake-plate-2-of-urizen-teach-these-souls-to-fly-n03696",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/N/N03/N03696_8.jpg",
            "thumbnailCopyright":"null",
            "concept_names":[
                "subject",
                "literature and fiction",
                "literature (not Shakespeare)",
                "Blake, William, 'Urizen'",
                "characters",
                "Enitharmon",
                "Orc",
                "people",
                "children",
                "baby",
                "actions: postures and motions",
                "flying",
                "actions: expressive",
                "holding hands",
                "adults",
                "woman",
                "society",
                "social comment",
                "freedom",
                "family",
                "mother and child",
                "symbols & personifications",
                "abstract concepts",
                "freedom - flying",
                "emotional states and conditions",
                "pity - Enitharmon",
                "society",
                "revolt - Orc",
                "religion and belief",
                "mysticism",
                "spirit"
            ]
        },
        "N04415":{
            "url":"http://www.tate.org.uk/art/artworks/maillol-torso-of-the-monument-to-blanqui-n04415",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/N/N04/N04415_8.jpg",
            "thumbnailCopyright":"\u00a9 ADAGP, Paris and DACS, London 2014",
            "concept_names":[
                "subject",
                "objects",
                "fine art and design, named works",
                "Maillol, Aristide, 'Monument to Blanqui'",
                "fine arts and music",
                "sculpture, classical",
                "people",
                "nudes",
                "female",
                "body",
                "torso",
                "adults",
                "woman",
                "society",
                "social comment",
                "freedom"
            ]
        },
        "P01898":{
            "url":"http://www.tate.org.uk/art/artworks/collins-island-p01898",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/P/P01/P01898_8.jpg",
            "thumbnailCopyright":"\u00a9 Tate",
            "concept_names":[
                "subject",
                "literature and fiction",
                "Shakespeare",
                "'The Tempest'",
                "people",
                "adults",
                "figure",
                "body",
                "head / face",
                "society",
                "social comment",
                "freedom",
                "nature",
                "seascapes and coasts",
                "island",
                "sea",
                "wave",
                "animals: features",
                "wing",
                "landscape",
                "wooded",
                "religion and belief",
                "magic and occultism",
                "oracle",
                "mysticism",
                "vision"
            ]
        },
        "P01915":{
            "url":"http://www.tate.org.uk/art/artworks/collins-fool-and-bird-p01915",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/P/P01/P01915_8.jpg",
            "thumbnailCopyright":"\u00a9 Tate",
            "concept_names":[
                "subject",
                "literature and fiction",
                "characters",
                "Fool",
                "people",
                "actions: postures and motions",
                "arm/arms raised",
                "standing",
                "adults",
                "man",
                "nature",
                "animals: birds",
                "bird - non-specific",
                "society",
                "dress: fantasy/fancy",
                "clown costume",
                "social comment",
                "freedom",
                "emotions, concepts and ideas",
                "emotions and human qualities",
                "creativity",
                "innocence",
                "symbols & personifications",
                "abstract concepts",
                "freedom - bird",
                "emotional states and conditions",
                "innocence - the Fool"
            ]
        },
        "P01916":{
            "url":"http://www.tate.org.uk/art/artworks/collins-bird-smoking-a-pipe-p01916",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/P/P01/P01916_8.jpg",
            "thumbnailCopyright":"\u00a9 Tate",
            "concept_names":[
                "subject",
                "nature",
                "animals: birds",
                "bird - non-specific",
                "objects",
                "furnishings",
                "chair",
                "table",
                "clothing and personal effects",
                "hat",
                "pipe",
                "fine arts and music",
                "picture",
                "society",
                "social comment",
                "freedom",
                "emotions, concepts and ideas",
                "emotions and human qualities",
                "happiness",
                "interiors",
                "domestic",
                "interior - non-specific",
                "leisure and pastimes",
                "recreational activities",
                "smoking"
            ]
        },
        "P11018":{
            "url":"http://www.tate.org.uk/art/artworks/collins-the-fool-p11018",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/P/P11/P11018_8.jpg",
            "thumbnailCopyright":"\u00a9 Tate",
            "concept_names":[
                "subject",
                "literature and fiction",
                "characters",
                "Fool",
                "nature",
                "animals: birds",
                "bird - non-specific",
                "people",
                "actions: processes and functions",
                "carrying",
                "body",
                "heart",
                "adults",
                "man",
                "actions: postures and motions",
                "walking",
                "society",
                "dress: fantasy/fancy",
                "clown costume",
                "social comment",
                "freedom",
                "symbols & personifications",
                "abstract concepts",
                "freedom - bird",
                "emotional states and conditions",
                "innocence - the Fool",
                "love - heart",
                "emotions, concepts and ideas",
                "emotions and human qualities",
                "innocence",
                "love",
                "leisure and pastimes",
                "music and entertainment",
                "music"
            ]
        },
        "P11020":{
            "url":"http://www.tate.org.uk/art/artworks/collins-fool-with-a-bird-p11020",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/P/P11/P11020_8.jpg",
            "thumbnailCopyright":"\u00a9 Tate",
            "concept_names":[
                "subject",
                "literature and fiction",
                "characters",
                "Fool",
                "religion and belief",
                "classical myths: gods and heroes",
                "Mercury / Hermes",
                "nature",
                "animals: birds",
                "bird - non-specific",
                "society",
                "social comment",
                "freedom",
                "symbols & personifications",
                "abstract concepts",
                "freedom - bird",
                "emotional states and conditions",
                "innocence - the Fool",
                "emotions, concepts and ideas",
                "emotions and human qualities",
                "innocence",
                "people",
                "adults",
                "man"
            ]
        },
        "P11945":{
            "url":"http://www.tate.org.uk/art/artworks/hamilton-finlay-no-title-p11945",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/P/P11/P11945_8.jpg",
            "thumbnailCopyright":"\u00a9 Estate of Ian Hamilton Finlay",
            "concept_names":[
                "subject",
                "places",
                "UK cities, towns and villages",
                "Lanark, Little Sparta",
                "UK counties",
                "Lanarkshire, South",
                "UK countries and regions",
                "Scotland",
                "society",
                "social comment",
                "freedom",
                "government and politics",
                "revolution",
                "symbols & personifications",
                "inscriptions",
                "printed text",
                "abstraction",
                "non-representational",
                "text"
            ]
        },
        "P77393":{
            "url":"http://www.tate.org.uk/art/artworks/holzer-no-title-p77393",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/P/P77/P77393_8.jpg",
            "thumbnailCopyright":"\u00a9 Jenny Holzer",
            "concept_names":[
                "subject",
                "society",
                "social comment",
                "freedom",
                "abstraction",
                "non-representational",
                "text"
            ]
        },
        "P77693":{
            "url":"http://www.tate.org.uk/art/artworks/bourgeois-woman-with-suitcase-p77693",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/P/P77/P77693_8.jpg",
            "thumbnailCopyright":"\u00a9 The Easton Foundation",
            "concept_names":[
                "subject",
                "architecture",
                "townscapes, man-made features",
                "building - non-specific",
                "street",
                "society",
                "birth to death",
                "childhood",
                "social comment",
                "freedom",
                "emotions, concepts and ideas",
                "emotions and human qualities",
                "courage",
                "isolation",
                "objects",
                "clothing and personal effects",
                "suitcase",
                "people",
                "actions: postures and motions",
                "walking",
                "adults",
                "woman"
            ]
        },
        "T01513":{
            "url":"http://www.tate.org.uk/art/artworks/klein-ikb-79-t01513",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/T/T01/T01513_8.jpg",
            "thumbnailCopyright":"\u00a9 ADAGP, Paris and DACS, London 2014",
            "concept_names":[
                "subject",
                "abstraction",
                "non-representational",
                "colour",
                "society",
                "social comment",
                "freedom",
                "emotions, concepts and ideas",
                "universal concepts",
                "void"
            ]
        },
        "T02186":{
            "url":"http://www.tate.org.uk/art/artworks/gabo-first-model-for-a-monument-to-the-unknown-political-prisoner-t02186",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/T/T02/T02186_8.jpg",
            "thumbnailCopyright":"The Work of Naum Gabo \u00a9 Nina & Graham Williams/Tate, London 2014",
            "concept_names":[
                "subject",
                "objects",
                "scientific and measuring",
                "architectural model",
                "society",
                "government and politics",
                "democracy",
                "political belief",
                "political prisoner",
                "totalitarianism",
                "social comment",
                "freedom",
                "persecution",
                "crime and punishment",
                "prisoner",
                "abstraction",
                "non-representational",
                "geometric",
                "architecture",
                "monuments",
                "monument",
                "history",
                "politics and society",
                "politics: Cold War, post-1945"
            ]
        },
        "T02187":{
            "url":"http://www.tate.org.uk/art/artworks/gabo-model-for-a-monument-to-the-unknown-political-prisoner-t02187",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/T/T02/T02187_8.jpg",
            "thumbnailCopyright":"The Work of Naum Gabo \u00a9 Nina & Graham Williams/Tate, London 2014",
            "concept_names":[
                "subject",
                "objects",
                "scientific and measuring",
                "architectural model",
                "society",
                "government and politics",
                "democracy",
                "political belief",
                "political prisoner",
                "totalitarianism",
                "social comment",
                "freedom",
                "persecution",
                "crime and punishment",
                "prisoner",
                "abstraction",
                "non-representational",
                "geometric",
                "architecture",
                "monuments",
                "monument",
                "history",
                "politics and society",
                "politics: Cold War, post-1945"
            ]
        },
        "T02332":{
            "url":"http://www.tate.org.uk/art/artworks/butler-working-model-for-the-unknown-political-prisoner-t02332",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/T/T02/T02332_8.jpg",
            "thumbnailCopyright":"\u00a9 The estate of Reg Butler",
            "concept_names":[
                "subject",
                "places",
                "cities, towns, villages (non-UK)",
                "Berlin - non-specific",
                "countries and continents",
                "Germany",
                "history",
                "military: World War II",
                "Holocaust",
                "politics and society",
                "politics: Cold War, post-1945",
                "society",
                "government and politics",
                "democracy",
                "political prisoner",
                "totalitarianism",
                "social comment",
                "freedom",
                "persecution",
                "people",
                "adults",
                "figure",
                "abstraction",
                "from recognisable sources",
                "figure",
                "landscape",
                "architecture",
                "monuments",
                "monument",
                "nature",
                "landscape",
                "rocky"
            ]
        },
        "T03388":{
            "url":"http://www.tate.org.uk/art/artworks/rainer-untitled-body-language-t03388",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/T/T03/T03388_8.jpg",
            "thumbnailCopyright":"\u00a9 Arnulf Rainer",
            "concept_names":[
                "subject",
                "people",
                "named individuals",
                "Rainer, Arnulf",
                "adults",
                "man",
                "portraits",
                "self-portraits",
                "society",
                "education, science and learning",
                "anthropology",
                "social comment",
                "contemporary society",
                "freedom",
                "health and welfare",
                "psychiatry",
                "work and occupations",
                "arts and entertainment",
                "artist, multi-media",
                "emotions, concepts and ideas",
                "formal qualities",
                "defacement",
                "gestural",
                "movement",
                "photographic",
                "emotions and human qualities",
                "subconscious",
                "universal concepts",
                "violence"
            ]
        },
        "T03495":{
            "url":"http://www.tate.org.uk/art/artworks/lipchitz-david-and-goliath-on-a-column-t03495",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/T/T03/T03495_8.jpg",
            "thumbnailCopyright":"\u00a9 The estate of Jacques Lipchitz, courtesy, Marlborough Gallery, New York",
            "concept_names":[
                "subject",
                "religion and belief",
                "Bible: Old Testament",
                "1 Samuel, chapter 17",
                "David",
                "Goliath",
                "symbols & personifications",
                "politics",
                "Nazism - giant",
                "Nazism - swastika",
                "inscriptions",
                "swastika",
                "society",
                "social comment",
                "anti-semitism",
                "freedom",
                "persecution",
                "government and politics",
                "fascism",
                "people",
                "actions: expressive",
                "fighting",
                "adults",
                "man",
                "abstraction",
                "from recognisable sources",
                "figure",
                "nature",
                "animals: fantastic",
                "giant",
                "history",
                "politics and society",
                "politics: Nazi Germany, 1933-45"
            ]
        },
        "T03512":{
            "url":"http://www.tate.org.uk/art/artworks/lipchitz-first-study-for-toward-a-new-world-t03512",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/T/T03/T03512_8.jpg",
            "thumbnailCopyright":"\u00a9 The estate of Jacques Lipchitz, courtesy, Marlborough Gallery, New York",
            "concept_names":[
                "subject",
                "leisure and pastimes",
                "music and entertainment",
                "dance",
                "people",
                "adults",
                "figure",
                "abstraction",
                "from recognisable sources",
                "figure",
                "society",
                "social comment",
                "freedom",
                "government and politics",
                "political belief",
                "emotions, concepts and ideas",
                "emotions and human qualities",
                "hope",
                "history",
                "politics and society",
                "politics: Communism"
            ]
        },
        "T03514":{
            "url":"http://www.tate.org.uk/art/artworks/lipchitz-study-for-a-monument-t03514",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/T/T03/T03514_8.jpg",
            "thumbnailCopyright":"\u00a9 The estate of Jacques Lipchitz, courtesy, Marlborough Gallery, New York",
            "concept_names":[
                "subject",
                "leisure and pastimes",
                "music and entertainment",
                "dance",
                "people",
                "adults",
                "figure",
                "abstraction",
                "from recognisable sources",
                "figure",
                "society",
                "social comment",
                "freedom",
                "government and politics",
                "political belief",
                "emotions, concepts and ideas",
                "emotions and human qualities",
                "hope",
                "history",
                "politics and society",
                "politics: Communism"
            ]
        },
        "T03515":{
            "url":"http://www.tate.org.uk/art/artworks/lipchitz-david-and-goliath-t03515",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/T/T03/T03515_8.jpg",
            "thumbnailCopyright":"\u00a9 The estate of Jacques Lipchitz, courtesy, Marlborough Gallery, New York",
            "concept_names":[
                "subject",
                "religion and belief",
                "Bible: Old Testament",
                "1 Samuel, chapter 17",
                "David",
                "Goliath",
                "symbols & personifications",
                "politics",
                "Nazism - giant",
                "Nazism - swastika",
                "inscriptions",
                "swastika",
                "society",
                "social comment",
                "anti-semitism",
                "freedom",
                "persecution",
                "birth to death",
                "death",
                "government and politics",
                "fascism",
                "people",
                "actions: expressive",
                "attacking",
                "adults",
                "man",
                "abstraction",
                "from recognisable sources",
                "figure",
                "nature",
                "animals: fantastic",
                "giant",
                "history",
                "politics and society",
                "politics: Nazi Germany, 1933-45"
            ]
        },
        "T03594":{
            "url":"http://www.tate.org.uk/art/artworks/beuys-four-blackboards-t03594",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/T/T03/T03594_8.jpg",
            "thumbnailCopyright":"\u00a9 DACS, 2014",
            "concept_names":[
                "subject",
                "objects",
                "reading, writing, printed matter",
                "blackboard",
                "emotions, concepts and ideas",
                "emotions and human qualities",
                "creativity",
                "formal qualities",
                "diagrammatic",
                "universal concepts",
                "existence",
                "society",
                "government and politics",
                "democracy",
                "social comment",
                "ecology",
                "freedom",
                "morality",
                "symbols & personifications",
                "inscriptions",
                "notes and diagrams"
            ]
        },
        "T06562":{
            "url":"http://www.tate.org.uk/art/artworks/barry-the-glorious-sextumvirate-t06562",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/T/T06/T06562_8.jpg",
            "thumbnailCopyright":"null",
            "concept_names":[
                "subject",
                "people",
                "named individuals",
                "Aristotle",
                "Brutus, Lucius Junius",
                "Brutus, Marcus Junius",
                "Cato the Younger",
                "Columbus, Christopher",
                "Epaminondas",
                "Harvey, William",
                "Hippocrates",
                "Locke, John",
                "Lucius Junius Brutus",
                "More, Thomas, Sir",
                "Plato",
                "Shaftesbury, Anthony Ashley-Cooper, Earl of",
                "Socrates",
                "Zeno",
                "groups",
                "group",
                "portraits",
                "groups",
                "adults",
                "man",
                "literature and fiction",
                "literature (not Shakespeare)",
                "Swift, Jonathan, 'Gulliver's Travels'",
                "religion and belief",
                "universal religious imagery",
                "angel",
                "work and occupations",
                "literary",
                "author",
                "educational and scientific",
                "philosopher",
                "public service",
                "politician - non-specific",
                "symbols & personifications",
                "inscriptions",
                "caption",
                "society",
                "government and politics",
                "democracy",
                "political belief",
                "social comment",
                "freedom",
                "objects",
                "clothing and personal effects",
                "toga"
            ]
        },
        "T06563":{
            "url":"http://www.tate.org.uk/art/artworks/barry-lord-baltimore-and-the-group-of-legislators-t06563",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/T/T06/T06563_8.jpg",
            "thumbnailCopyright":"null",
            "concept_names":[
                "subject",
                "people",
                "named individuals",
                "Alfred the Great, King",
                "Baltimore, Cacilius Clalvert, second Baron",
                "Berkeley, George, Bishop of Cloyne",
                "Franklin, Benjamin",
                "Lycurgus of Sparta",
                "Marcus Aurelius",
                "Molyneux, William",
                "Numa Pompilius",
                "Penn, William",
                "groups",
                "group",
                "portraits",
                "groups",
                "adults",
                "man",
                "work and occupations",
                "religious",
                "bishop",
                "royalty and social rank",
                "king",
                "public service",
                "politician - non-specific",
                "symbols & personifications",
                "inscriptions",
                "caption",
                "objects",
                "clothing and personal effects",
                "cloak",
                "religious and ceremonial",
                "crown",
                "mitre",
                "reading, writing, printed matter",
                "document - non-specific",
                "nature",
                "weather",
                "cloud",
                "society",
                "social comment",
                "freedom",
                "leisure and pastimes",
                "recreational activities",
                "reading",
                "history",
                "politics and society",
                "society: America, colonization, 17th c."
            ]
        },
        "T06572":{
            "url":"http://www.tate.org.uk/art/artworks/barry-the-phoenix-or-the-resurrection-of-freedom-t06572",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/T/T06/T06572_8.jpg",
            "thumbnailCopyright":"null",
            "concept_names":[
                "subject",
                "objects",
                "reading, writing, printed matter",
                "book - non-specific",
                "scroll",
                "religious and ceremonial",
                "gravestone / tomb",
                "fine arts and music",
                "sculpture",
                "agriculture, gardening & fishing",
                "scythe",
                "architecture",
                "periods and styles",
                "classical",
                "religious",
                "temple",
                "ruins",
                "townscape",
                "townscapes, man-made features",
                "townscape, distant",
                "society",
                "social comment",
                "colonialism",
                "freedom",
                "satire",
                "birth to death",
                "mourning",
                "government and politics",
                "revolution",
                "emotions, concepts and ideas",
                "emotions and human qualities",
                "despair",
                "hope",
                "nature",
                "landscape",
                "farmland",
                "hill",
                "plants and flowers",
                "garland",
                "animals: mammals",
                "horse",
                "sheep",
                "animals: fantastic",
                "phoenix",
                "water: inland",
                "river",
                "people",
                "actions: postures and motions",
                "flying",
                "standing",
                "walking",
                "groups",
                "group",
                "adults",
                "man",
                "woman",
                "actions: expressive",
                "pointing",
                "work and occupations",
                "agriculture and fishing",
                "ploughing",
                "shepherd / shepherdess",
                "history",
                "politics and society",
                "politics: America, Declaration of Independence, 1776",
                "symbols & personifications",
                "birth to death",
                "rebirth - phoenix",
                "abstract concepts",
                "time - old man"
            ]
        },
        "T07906":{
            "url":"http://www.tate.org.uk/art/artworks/dalwood-situationist-apartment-may-68-t07906",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/T/T07/T07906_8.jpg",
            "thumbnailCopyright":"\u00a9 Dexter Dalwood, courtesy Simon Lee Gallery, London & Hong Kong",
            "concept_names":[
                "subject",
                "people",
                "named individuals",
                "Debord, Guy",
                "portraits",
                "individuals: male",
                "objects",
                "fine art and design, named works",
                "Twombly, Cy, painting, 'Untitled (New York City)'",
                "Twombly, Cy, painting, 'Untitled (Rome)'",
                "furnishings",
                "bed",
                "bedspread",
                "mattress",
                "pillow",
                "rug",
                "reading, writing, printed matter",
                "poster",
                "interiors",
                "domestic",
                "bedroom",
                "society",
                "social comment",
                "consumerism",
                "freedom",
                "lifestyle and culture",
                "cultural icon",
                "architecture",
                "features",
                "door",
                "townscapes, man-made features",
                "graffiti",
                "emotions, concepts and ideas",
                "universal concepts",
                "irony",
                "formal qualities",
                "photographic",
                "history",
                "politics and society",
                "politics: Situationist International, 1960s",
                "protests and unrest: Paris uprising, May 1968"
            ]
        },
        "T12026":{
            "url":"http://www.tate.org.uk/art/artworks/hepworth-maquette-for-the-unknown-political-prisoner-t12026",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/T/T12/T12026_8.jpg",
            "thumbnailCopyright":"\u00a9 Bowness, Hepworth Estate",
            "concept_names":[
                "subject",
                "emotions, concepts and ideas",
                "emotions and human qualities",
                "courage",
                "people",
                "adults",
                "figure",
                "abstraction",
                "from recognisable sources",
                "figure",
                "non-representational",
                "irregular forms",
                "society",
                "social comment",
                "freedom",
                "government and politics",
                "political prisoner"
            ]
        },
        "T12321":{
            "url":"http://www.tate.org.uk/art/artworks/turner-the-northampton-election-6-december-1830-t12321",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/T/T12/T12321_8.jpg",
            "thumbnailCopyright":"null",
            "concept_names":[
                "subject",
                "architecture",
                "periods and styles",
                "Baroque",
                "religious",
                "church",
                "features",
                "dome",
                "tower",
                "residential",
                "hotel",
                "townscapes, man-made features",
                "street",
                "places",
                "UK countries and regions",
                "England",
                "UK cities, towns and villages",
                "Northampton, All Saints' Church",
                "UK counties",
                "Northamptonshire",
                "people",
                "named individuals",
                "Spencer, John Charles Spencer, Viscount Althorp, 3rd Earl",
                "actions: processes and functions",
                "carrying",
                "children",
                "child",
                "groups",
                "crowd",
                "adults",
                "man",
                "woman",
                "actions: postures and motions",
                "sitting",
                "standing",
                "work and occupations",
                "royalty and social rank",
                "aristocrat",
                "public service",
                "politician, Member of Parliament",
                "society",
                "transport: land",
                "carriage",
                "government and politics",
                "democracy",
                "election",
                "patriotism",
                "social comment",
                "freedom",
                "objects",
                "furnishings",
                "chair",
                "religious and ceremonial",
                "flag - non-specific",
                "flag, Union Flag",
                "rosette",
                "wreath",
                "emotions, concepts and ideas",
                "emotions and human qualities",
                "happiness",
                "triumph",
                "nature",
                "animals: mammals",
                "horse",
                "weather",
                "sunbeam",
                "symbols & personifications",
                "inscriptions",
                "name of place",
                "phrase",
                "history",
                "politics and society",
                "politics: Lord Althorp, election, Dec 1830"
            ]
        },
        "T12430":{
            "url":"http://www.tate.org.uk/art/artworks/koller-universal-cultural-futurological-operation-t12430",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/T/T12/T12430_8.jpg",
            "thumbnailCopyright":"\u00a9 The estate of J\u00falius Koller",
            "concept_names":[
                "subject",
                "people",
                "named individuals",
                "Koller, J\u00falius",
                "adults",
                "man",
                "portraits",
                "self-portraits",
                "work and occupations",
                "arts and entertainment",
                "artist, multi-media",
                "objects",
                "clothing and personal effects",
                "badge",
                "spectacles",
                "society",
                "social comment",
                "freedom",
                "emotions, concepts and ideas",
                "formal qualities",
                "photographic",
                "history",
                "politics and society",
                "politics: Communism"
            ]
        },
        "T12431":{
            "url":"http://www.tate.org.uk/art/artworks/koller-continuationstoop-universal-cultural-futurological-operation-t12431",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/T/T12/T12431_8.jpg",
            "thumbnailCopyright":"\u00a9 The estate of J\u00falius Koller",
            "concept_names":[
                "subject",
                "people",
                "named individuals",
                "Koller, J\u00falius",
                "actions: postures and motions",
                "crouching",
                "adults",
                "man",
                "portraits",
                "self-portraits",
                "work and occupations",
                "arts and entertainment",
                "artist, multi-media",
                "architecture",
                "features",
                "door",
                "society",
                "social comment",
                "freedom",
                "emotions, concepts and ideas",
                "formal qualities",
                "photographic",
                "history",
                "politics and society",
                "politics: Communism"
            ]
        },
        "T12432":{
            "url":"http://www.tate.org.uk/art/artworks/koller-archaeological-monument-presence-ufo-t12432",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/T/T12/T12432_8.jpg",
            "thumbnailCopyright":"\u00a9 The estate of J\u00falius Koller",
            "concept_names":[
                "subject",
                "society",
                "education, science and learning",
                "archaeology",
                "social comment",
                "freedom",
                "transport: air",
                "spacecraft",
                "emotions, concepts and ideas",
                "formal qualities",
                "photographic"
            ]
        },
        "T12434":{
            "url":"http://www.tate.org.uk/art/artworks/koller-pop-ufo-t12434",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/T/T12/T12434_8.jpg",
            "thumbnailCopyright":"\u00a9 The estate of J\u00falius Koller",
            "concept_names":[
                "subject",
                "objects",
                "reading, writing, printed matter",
                "document - non-specific",
                "society",
                "social comment",
                "freedom",
                "symbols & personifications",
                "inscriptions",
                "name of artist",
                "printed text",
                "history",
                "politics and society",
                "politics: Communism",
                "abstraction",
                "non-representational",
                "text"
            ]
        },
        "T12435":{
            "url":"http://www.tate.org.uk/art/artworks/koller-1971-t12435",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/T/T12/T12435_8.jpg",
            "thumbnailCopyright":"\u00a9 The estate of J\u00falius Koller",
            "concept_names":[
                "subject",
                "objects",
                "reading, writing, printed matter",
                "document - non-specific",
                "society",
                "social comment",
                "freedom",
                "symbols & personifications",
                "inscriptions",
                "name of artist",
                "printed text",
                "history",
                "politics and society",
                "politics: Communism"
            ]
        },
        "T12573":{
            "url":"http://www.tate.org.uk/art/artworks/koller-universal-fantastic-orientation-1-6-ufo-t12573",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/T/T12/T12573_8.jpg",
            "thumbnailCopyright":"\u00a9 The estate of J\u00falius Koller",
            "concept_names":[
                "subject",
                "people",
                "named individuals",
                "Koller, J\u00falius",
                "adults",
                "man",
                "portraits",
                "self-portraits",
                "places",
                "countries and continents",
                "Slovakia",
                "mythical, religious, fictional",
                "Ufomany",
                "work and occupations",
                "arts and entertainment",
                "artist, multi-media",
                "society",
                "social comment",
                "freedom",
                "nature",
                "landscape",
                "landscape - non-specific",
                "architecture",
                "townscapes, man-made features",
                "path",
                "emotions, concepts and ideas",
                "formal qualities",
                "photographic",
                "repetition",
                "objects",
                "reading, writing, printed matter",
                "placard",
                "clothing and personal effects",
                "spectacles",
                "history",
                "politics and society",
                "politics: Communism"
            ]
        },
        "T12748":{
            "url":"http://www.tate.org.uk/art/artworks/hirst-the-acquired-inability-to-escape-t12748",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/T/T12/T12748_8.jpg",
            "thumbnailCopyright":"\u00a9 Damien Hirst and Science Ltd. ",
            "concept_names":[
                "subject",
                "objects",
                "fine art and design, named works",
                "Bacon, Francis, paintings",
                "Graham, Dan, pavilion",
                "Haacke, Hans, 'Condensation Cube'",
                "Nauman, Bruce, 'Learned Helplessness in Rats, (Rock and Roll Drummer)",
                "domestic",
                "ashtray",
                "furnishings",
                "chair",
                "table",
                "clothing and personal effects",
                "cigarette",
                "cigarette lighter",
                "cigarette packet",
                "miscellaneous",
                "glass",
                "architecture",
                "residential",
                "cell",
                "industrial",
                "structure",
                "people",
                "diseases and conditions",
                "claustrophobia",
                "symbols & personifications",
                "birth to death",
                "death - ahstray",
                "abstract concepts",
                "energy - cigarette lighter",
                "society",
                "health and welfare",
                "drug use",
                "social comment",
                "freedom",
                "crime and punishment",
                "imprisonment",
                "birth to death",
                "mortality",
                "literature and fiction",
                "film, music and ballet",
                "film: Figgis, Mike, 'Internal Affairs'",
                "abstraction",
                "from recognisable sources",
                "man-made",
                "emotions, concepts and ideas",
                "universal concepts",
                "menace",
                "leisure and pastimes",
                "recreational activities",
                "smoking"
            ]
        },
        "T12989":{
            "url":"http://www.tate.org.uk/art/artworks/bruguera-tatlins-whisper-5-t12989",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/T/T12/T12989_8.jpg",
            "thumbnailCopyright":"\u00a9 Tania Bruguera",
            "concept_names":[
                "subject",
                "interiors",
                "public and municipal",
                "art gallery",
                "people",
                "groups",
                "crowd",
                "adults",
                "man",
                "woman",
                "emotions, concepts and ideas",
                "universal concepts",
                "enclosure",
                "power",
                "emotions and human qualities",
                "fear",
                "society",
                "social comment",
                "freedom",
                "government and politics",
                "political power",
                "nature",
                "animals: mammals",
                "horse",
                "work and occupations",
                "crime and punishment",
                "policeman / policewoman"
            ]
        },
        "T13312":{
            "url":"http://www.tate.org.uk/art/artworks/koller-question-mark-b-anti-painting-anti-text-t13312",
            "thumbnailUrl":"http://www.tate.org.uk/art/images/work/T/T13/T13312_8.jpg",
            "thumbnailCopyright":"\u00a9 The estate of J\u00falius Koller",
            "concept_names":[
                "subject",
                "society",
                "social comment",
                "freedom",
                "lifestyle and culture",
                "popular culture",
                "history",
                "politics and society",
                "politics: Communism",
                "politics: Warsaw Pact, 1968",
                "emotions, concepts and ideas",
                "emotions and human qualities",
                "uncertainty"
            ]
        },
        "T13425":{
            "url":"http://www.tate.org.uk/art/artworks/mcqueen-static-t13425",
            "thumbnailUrl":"null",
            "thumbnailCopyright":"null",
            "concept_names":[
                "subject",
                "places",
                "cities, towns, villages (non-UK)",
                "New York, Statue of Liberty",
                "countries and continents",
                "USA",
                "objects",
                "religious and ceremonial",
                "crown",
                "society",
                "social comment",
                "freedom",
                "people",
                "body",
                "head / face",
                "emotions, concepts and ideas",
                "formal qualities",
                "photographic",
                "nature",
                "landscape",
                "sky",
                "architecture",
                "monuments",
                "statue"
            ]
        }
    }
}




def get_hlac_related_tags_and_frequencies(match_details):
    hlac_related_tags = {}
    artworks = match_details["tagged_artworks_dict"]
    for artwork, artwork_details in artworks.items():
        subjects = artwork_details["concept_names"] #subjects becomes a list of strings
        print(type(subjects))
        for tag in subjects:
            print(tag)
            if tag in hlac_related_tags:
                hlac_related_tags[tag] += 1
            else:
                hlac_related_tags[tag] = 1
    with open("output/hlac_artworks_matches/232_related_tags.json", 'w') as file:
             file.write(json.dumps(hlac_related_tags))
    sorted_dict = {k: v for k, v in sorted(hlac_related_tags.items(), key=lambda item: item[1], reverse=True)}
    with open("output/hlac_artworks_matches/sorted_dict.json", 'w') as file:
         file.write(json.dumps(sorted_dict))
    return hlac_related_tags


hola = get_hlac_related_tags_and_frequencies(match_details)
print(hola)